import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const cities = [
  {
    id: "gdansk",
    name: "Gdańsk",
    shortDescription: "Piękne miasto nad morzem",
    longDescription: "Gdańsk to historyczne miasto z bogatą przeszłością",
    gallery: [
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/1.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/2.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/3.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/4.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/5.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/6.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/7.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/gallery/8.jpeg",
    ],
    coverImage:
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdansk/main.jpg",
    latitude: 54.352,
    longitude: 18.6466,
    population: 466000,
    area: 262.0,
    walkScore: 80.0,
    commuteTime: 30,
    neighborhoods: {
      create: [
        {
          id: "srodmiescie-gdansk",
          name: "Śródmieście",
          description: "Centrum miasta",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2500.0,
          walkScore: 90.0,
          commuteTime: 10,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-001",
                title: "Mieszkanie w centrum",
                address: "ul. Długa 12",
                description: "Przytulne mieszkanie w historycznym budynku",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 1500.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 50.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-002",
                title: "Mieszkanie z widokiem",
                address: "ul. Mariacka 5",
                description: "Mieszkanie z pięknym widokiem na miasto",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 1800.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-003",
                title: "Mieszkanie dla studentów",
                address: "ul. Słowackiego 20",
                description: "Mieszkanie idealne dla studentów",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 1200.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 40.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "wrzeszcz",
          name: "Wrzeszcz",
          description: "Dzielnica akademicka",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/wrzeszcz/main.jpg",
          averageRent: 2000.0,
          walkScore: 80.0,
          commuteTime: 15,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-004",
                title: "Mieszkanie blisko uczelni",
                address: "ul. Wita Stwosza 10",
                description: "Mieszkanie idealne dla studentów",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 1400.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 45.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-005",
                title: "Mieszkanie z ogrodem",
                address: "ul. Do Studzienki 15",
                description: "Mieszkanie z pięknym ogrodem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 1600.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 60.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-006",
                title: "Mieszkanie dla singla",
                address: "ul. Słowackiego 25",
                description: "Mieszkanie idealne dla singla",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 1000.0,
                bedrooms: 1,
                bathrooms: 1,
                squareFootage: 30.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "oliwa",
          name: "Oliwa",
          description: "Dzielnica z pięknymi parkami",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/wrzeszcz/main.jpg",
          averageRent: 2200.0,
          walkScore: 85.0,
          commuteTime: 12,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-007",
                title: "Mieszkanie w spokojnej okolicy",
                address: "ul. Grunwaldzka 50",
                description: "Mieszkanie w spokojnej okolicy",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 1700.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 65.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-008",
                title: "Mieszkanie z widokiem na park",
                address: "ul. Oliwska 30",
                description: "Mieszkanie z pięknym widokiem na park",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 1900.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-009",
                title: "Mieszkanie dla rodziny",
                address: "ul. Spacerowa 10",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 2000.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "przymorze",
          name: "Przymorze",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/przymorze/main.jpg",
          averageRent: 2500.0,
          walkScore: 90.0,
          commuteTime: 10,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-010",
                title: "Mieszkanie nad morzem",
                address: "ul. Hryniewickiego 20",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2000.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-011",
                title: "Mieszkanie z tarasem",
                address: "ul. Chłopska 15",
                description: "Mieszkanie z pięknym tarasem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 2200.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-012",
                title: "Mieszkanie dla par",
                address: "ul. Gdańska 10",
                description: "Mieszkanie idealne dla par",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 1800.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 50.0,
                availableFrom: new Date("2024-03-01"),
              },
              {
                id: "apt-013",
                title: "Mieszkanie dla singla",
                address: "ul. Chłopska 5",
                description: "Mieszkanie idealne dla singla",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 1500.0,
                bedrooms: 1,
                bathrooms: 1,
                squareFootage: 35.0,
                availableFrom: new Date("2024-04-01"),
              },
            ],
          },
        },
        {
          id: "nowy-port",
          name: "Nowy Port",
          description: "Dzielnica portowa",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/nowy-port/main.webp",
          averageRent: 2300.0,
          walkScore: 80.0,
          commuteTime: 15,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-014",
                title: "Mieszkanie w okolicy portu",
                address: "ul. Na Stępce 25",
                description: "Mieszkanie w okolicy portu",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 1900.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 65.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-015",
                title: "Mieszkanie z widokiem na port",
                address: "ul. Letnica 10",
                description: "Mieszkanie z pięknym widokiem na port",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 2100.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-016",
                title: "Mieszkanie dla singla",
                address: "ul. Gdyńska 5",
                description: "Mieszkanie idealne dla singla",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 1600.0,
                bedrooms: 1,
                bathrooms: 1,
                squareFootage: 35.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "stogi",
          name: "Stogi",
          description: "Dzielnica przemysłowa",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/stogi/main.jpg",
          averageRent: 2000.0,
          walkScore: 75.0,
          commuteTime: 20,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-017",
                title: "Mieszkanie w okolicy przemysłu",
                address: "ul. Stogi 30",
                description: "Mieszkanie w okolicy przemysłu",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 1700.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 60.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-018",
                title: "Mieszkanie z widokiem na tereny zielone",
                address: "ul. Słowackiego 40",
                description: "Mieszkanie z pięknym widokiem na tereny zielone",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 1900.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 65.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-019",
                title: "Mieszkanie dla rodziny",
                address: "ul. Spacerowa 20",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 2000.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
      ],
    },
  },
  {
    id: "gdynia",
    name: "Gdynia",
    shortDescription: "Miasto portowe",
    longDescription: "Gdynia to dynamicznie rozwijające się miasto",
    gallery: [
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/1.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/2.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/3.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/4.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/5.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/6.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/7.jpg",
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/gallery/8.jpg",
    ],
    coverImage:
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/gdynia/main.jpg",
    latitude: 54.52,
    longitude: 18.5333,
    population: 245000,
    area: 135.0,
    walkScore: 85.0,
    commuteTime: 25,
    neighborhoods: {
      create: [
        {
          id: "srodmiescie-gdynia",
          name: "Śródmieście",
          description: "Centrum miasta",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2800.0,
          walkScore: 95.0,
          commuteTime: 5,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-020",
                title: "Mieszkanie w centrum",
                address: "ul. Świętojańska 10",
                description: "Przytulne mieszkanie w historycznym budynku",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2200.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-021",
                title: "Mieszkanie z widokiem na morze",
                address: "ul. 10 Lutego 20",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 2500.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-022",
                title: "Mieszkanie dla singla",
                address: "ul. Władysława IV 5",
                description: "Mieszkanie idealne dla singla",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 2000.0,
                bedrooms: 1,
                bathrooms: 1,
                squareFootage: 35.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "redlowo",
          name: "Redłowo",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 3000.0,
          walkScore: 90.0,
          commuteTime: 10,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-023",
                title: "Mieszkanie nad morzem",
                address: "ul. Redłowska 15",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2800.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-024",
                title: "Mieszkanie z tarasem",
                address: "ul. Kępa Redłowska 10",
                description: "Mieszkanie z pięknym tarasem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3200.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-025",
                title: "Mieszkanie dla par",
                address: "ul. Redłowska 20",
                description: "Mieszkanie idealne dla par",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 2400.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 50.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "wzgorze-sw-maksymiliana",
          name: "Wzgórze św. Maksymiliana",
          description: "Dzielnica z centrum handlowym",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2900.0,
          walkScore: 95.0,
          commuteTime: 5,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-026",
                title: "Mieszkanie blisko centrum handlowego",
                address: "ul. Morska 25",
                description: "Mieszkanie w okolicy Riviera",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2600.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-027",
                title: "Mieszkanie z widokiem na miasto",
                address: "ul. Wzgórze św. Maksymiliana 10",
                description: "Mieszkanie z pięknym widokiem na miasto",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3000.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-028",
                title: "Mieszkanie dla rodziny",
                address: "ul. Wzgórze św. Maksymiliana 20",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 3200.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 90.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "dzialki-lesne",
          name: "Działki Leśne",
          description: "Dzielnica willowa",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2500.0,
          walkScore: 80.0,
          commuteTime: 15,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-029",
                title: "Mieszkanie w willi",
                address: "ul. Leśna 15",
                description: "Mieszkanie w pięknej willi",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2300.0,
                bedrooms: 4,
                bathrooms: 3,
                squareFootage: 100.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-030",
                title: "Mieszkanie z ogrodem",
                address: "ul. Sosnowa 10",
                description: "Mieszkanie z pięknym ogrodem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 2800.0,
                bedrooms: 4,
                bathrooms: 3,
                squareFootage: 120.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-031",
                title: "Mieszkanie dla singla",
                address: "ul. Dębowa 20",
                description: "Mieszkanie idealne dla singla",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 1800.0,
                bedrooms: 1,
                bathrooms: 1,
                squareFootage: 35.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "kamienna-gora",
          name: "Kamienna Góra",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 3200.0,
          walkScore: 90.0,
          commuteTime: 10,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-032",
                title: "Mieszkanie nad morzem",
                address: "ul. Kamienna Góra 10",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 3000.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-033",
                title: "Mieszkanie z tarasem",
                address: "ul. Kamienna Góra 20",
                description: "Mieszkanie z pięknym tarasem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3500.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-034",
                title: "Mieszkanie dla par",
                address: "ul. Kamienna Góra 25",
                description: "Mieszkanie idealne dla par",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 2800.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 50.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "okswyie",
          name: "Oksywie",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 3100.0,
          walkScore: 90.0,
          commuteTime: 15,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-035",
                title: "Mieszkanie nad morzem",
                address: "ul. Oksywie 15",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2900.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-036",
                title: "Mieszkanie z widokiem na port",
                address: "ul. Oksywie 20",
                description: "Mieszkanie z pięknym widokiem na port",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3300.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-037",
                title: "Mieszkanie dla rodziny",
                address: "ul. Oksywie 25",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 3500.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 90.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
      ],
    },
  },
  {
    id: "sopot",
    name: "Sopot",
    shortDescription: "Miasto nad morzem",
    longDescription: "Sopot to popularne miasto wypoczynkowe",
    gallery: [
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
    ],
    coverImage:
      "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/cities/sopot/main.jpg",
    latitude: 54.4433,
    longitude: 18.5667,
    population: 38000,
    area: 17.31,
    walkScore: 85.0,
    commuteTime: 20,
    neighborhoods: {
      create: [
        {
          id: "dolny-sopot",
          name: "Dolny Sopot",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2800.0,
          walkScore: 90.0,
          commuteTime: 10,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-038",
                title: "Mieszkanie nad morzem",
                address: "ul. 3 Maja 10",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2500.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-039",
                title: "Mieszkanie z tarasem",
                address: "ul. Bohaterów Monte Cassino 20",
                description: "Mieszkanie z pięknym tarasem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 2800.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-040",
                title: "Mieszkanie dla par",
                address: "ul. Morska 15",
                description: "Mieszkanie idealne dla par",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 2200.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 50.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "gorny-sopot",
          name: "Górny Sopot",
          description: "Dzielnica z pięknymi parkami",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 3000.0,
          walkScore: 85.0,
          commuteTime: 12,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-041",
                title: "Mieszkanie w spokojnej okolicy",
                address: "ul. Mikołaja Reja 25",
                description: "Mieszkanie w spokojnej okolicy",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2700.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-042",
                title: "Mieszkanie z widokiem na park",
                address: "ul. Jacka Malczewskiego 10",
                description: "Mieszkanie z pięknym widokiem na park",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3100.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-043",
                title: "Mieszkanie dla rodziny",
                address: "ul. Spacerowa 20",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 3300.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "kamienny-potok",
          name: "Kamienny Potok",
          description: "Dzielnica z zielenią",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2600.0,
          walkScore: 80.0,
          commuteTime: 15,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-044",
                title: "Mieszkanie w spokojnej okolicy",
                address: "ul. Kamienny Potok 15",
                description: "Mieszkanie w spokojnej okolicy",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2400.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 65.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-045",
                title: "Mieszkanie z ogrodem",
                address: "ul. Oskara Kolberga 10",
                description: "Mieszkanie z pięknym ogrodem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 2900.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-046",
                title: "Mieszkanie dla singla",
                address: "ul. Władysława Cieszyńskiego 5",
                description: "Mieszkanie idealne dla singla",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 2000.0,
                bedrooms: 1,
                bathrooms: 1,
                squareFootage: 35.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "karlikowo",
          name: "Karlikowo",
          description: "Dzielnica willowa",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 3200.0,
          walkScore: 85.0,
          commuteTime: 12,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-047",
                title: "Mieszkanie w willi",
                address: "ul. Karlikowska 20",
                description: "Mieszkanie w pięknej willi",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 3000.0,
                bedrooms: 4,
                bathrooms: 3,
                squareFootage: 100.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-048",
                title: "Mieszkanie z ogrodem",
                address: "ul. Wyścigi 10",
                description: "Mieszkanie z pięknym ogrodem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 3500.0,
                bedrooms: 4,
                bathrooms: 3,
                squareFootage: 120.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-049",
                title: "Mieszkanie dla rodziny",
                address: "ul. Wyścigi 20",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 3800.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 90.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "brodwino",
          name: "Brodwino",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 2900.0,
          walkScore: 90.0,
          commuteTime: 10,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-050",
                title: "Mieszkanie nad morzem",
                address: "ul. Oskara Kolberga 25",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2600.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 70.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-051",
                title: "Mieszkanie z tarasem",
                address: "ul. Władysława Cieszyńskiego 15",
                description: "Mieszkanie z pięknym tarasem",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3100.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-052",
                title: "Mieszkanie dla par",
                address: "ul. Oskara Kolberga 10",
                description: "Mieszkanie idealne dla par",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi"],
                monthlyRent: 2400.0,
                bedrooms: 2,
                bathrooms: 1,
                squareFootage: 50.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
        {
          id: "swiemirowo",
          name: "Świemirowo",
          description: "Dzielnica nad morzem",
          thumbnail:
            "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/neighborhoods/srodmiescie/main.jpg",
          averageRent: 3100.0,
          walkScore: 90.0,
          commuteTime: 15,
          features: [
            "Close to public transportation",
            "Vibrant nightlife",
            "Shopping districts",
            "Excellent dining options",
            "Parks and green spaces",
            "Cultural attractions",
          ],
          apartments: {
            create: [
              {
                id: "apt-053",
                title: "Mieszkanie nad morzem",
                address: "ul. Mikołaja Reja 30",
                description: "Mieszkanie z pięknym widokiem na morze",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV"],
                monthlyRent: 2900.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 75.0,
                availableFrom: new Date("2024-01-01"),
              },
              {
                id: "apt-054",
                title: "Mieszkanie z widokiem na port",
                address: "ul. Mikołaja Reja 35",
                description: "Mieszkanie z pięknym widokiem na port",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Pralka"],
                monthlyRent: 3300.0,
                bedrooms: 3,
                bathrooms: 2,
                squareFootage: 80.0,
                availableFrom: new Date("2024-02-01"),
              },
              {
                id: "apt-055",
                title: "Mieszkanie dla rodziny",
                address: "ul. Mikołaja Reja 40",
                description: "Mieszkanie idealne dla rodziny",
                thumbnail:
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments//main.jpg",
                gallery: [
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/1.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/2.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/3.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/4.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/5.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/6.jpg",
                  "https://efvivjdsmnjmucdqmpvi.supabase.co/storage/v1/object/public/apartments/gallery/7.jpg",
                ],
                amenities: ["Wi-Fi", "TV", "Ogród"],
                monthlyRent: 3500.0,
                bedrooms: 4,
                bathrooms: 2,
                squareFootage: 90.0,
                availableFrom: new Date("2024-03-01"),
              },
            ],
          },
        },
      ],
    },
  },
];

async function main() {
  console.log("Start seeding ...");

  //  Upsert cities
  for (const city of cities) {
    await prisma.city.upsert({
      where: { id: city.id },
      update: {},
      create: {
        ...city,
        neighborhoods: {
          create: city.neighborhoods.create.map((neighborhood) => ({
            ...neighborhood,
            apartments: {
              create: neighborhood.apartments.create,
            },
          })),
        },
      },
    });
  }
  console.log("Cities seeded.");
  // //  Upsert neighborhoods

  console.log("Seeding finished.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
