("");
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { MainNavigation } from "@/components/main-navigation";
import Footer from "@/components/footer";
import SearchContextProvider from "@/contexts/search-context-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-auto flex min-h-screen flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchContextProvider>
          <MainNavigation />
          {children}
          <Footer />
        </SearchContextProvider>
      </body>
    </html>
  );
}
