("");
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { MainNavigation } from "@/components/main-navigation";
import Footer from "@/components/footer";
import SearchContextProvider from "@/contexts/search-context-provider";
import NeighborhoodContextProvider from "@/contexts/neighborhood-context-provider";
import prisma from "@/lib/db";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch neighborhoods from the database
  const neighborhoods = await prisma.neighborhood.findMany();
  // Convert neighborhoods to a plain object
  const plainNeighborhoods = neighborhoods.map((neighborhood) => ({
    ...neighborhood,
    averageRent: neighborhood.averageRent?.toNumber(),
    walkScore: neighborhood.walkScore?.toNumber(),
    commuteTime: neighborhood.commuteTime?.toNumber(),
  }));

  return (
    <html lang="en">
      <body
        className={`mx-auto flex min-h-screen flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchContextProvider>
          <NeighborhoodContextProvider data={plainNeighborhoods}>
            <MainNavigation />
            {children}
            <Footer />
          </NeighborhoodContextProvider>
        </SearchContextProvider>
      </body>
    </html>
  );
}
